name: Compile Checks

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '**.py'

jobs:
  compile-checks:
    name: Check project compiles
    strategy:
      matrix:
        preset:
          - nucleo-debug-eth
          - nucleo-release-eth
          - nucleo-relwithdebinfo-eth
          - board-debug-eth
          - board-release-eth
          - board-relwithdebinfo-eth
          - simulator
      fail-fast: false
    uses: ./.github/workflows/build.yml
    with:
      preset: ${{ matrix.preset }}
